post_install() {
    echo -e "\n** The files have been installed in /etc/skel/.config/leftwm **\n"
    leftwm-theme update
    leftwm-theme install "master-pywal-theme"
    leftwm-theme install "mpt-tablet"
    leftwm-theme apply "master-pywal-theme"
}

post_upgrade() {
    echo -e "\n** The files have been installed in /etc/skel/.config/leftwm **\n"
    leftwm-theme upgrade
    #leftwm-theme apply "master-pywal-theme"
}
